<template>
  <div class="app-container"><el-card shadow="never">
    <el-form :inline="true" :model="query"><el-form-item label="发票号"><el-input v-model="query.invoiceNo" clearable /></el-form-item><el-form-item label="客户"><el-input v-model="query.customerName" clearable /></el-form-item><el-form-item label="日期"><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable style="width:120px"><el-option v-for="x in SalesFinanceDocumentStatusEnum.items" :key="x.value" :label="x.label" :value="x.value" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form>
    <!-- 扩展位：后续新增/编辑发票按钮放在此处。 -->
    <el-table v-loading="loading" :data="rows" border><el-table-column prop="invoiceNo" label="发票号" min-width="150"/><el-table-column prop="orderId" label="订单" width="100"/><el-table-column prop="customerName" label="客户" min-width="150"/><el-table-column prop="invoiceDate" label="日期" width="120"/><el-table-column label="金额" width="110" align="right"><template #default="{row}">{{money(row.invoiceAmount)}}</template></el-table-column><el-table-column label="税额" width="110" align="right"><template #default="{row}">{{money(row.taxAmount)}}</template></el-table-column><el-table-column label="合计" width="110" align="right"><template #default="{row}">{{money(row.totalAmount)}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="SalesFinanceDocumentStatusEnum.getTagProps(row.status).type">{{SalesFinanceDocumentStatusEnum.getLabel(row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="print(row.invoiceId)">打印</el-button><el-button link @click="detail(row.invoiceId)">详情</el-button></template></el-table-column></el-table>
    <el-pagination v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :total="total" layout="total, sizes, prev, pager, next" @change="load" />
  </el-card><el-dialog v-model="visible" title="发票详情" width="680px"><el-descriptions v-if="current" :column="2" border><el-descriptions-item v-for="x in details" :key="x.label" :label="x.label">{{x.value}}</el-descriptions-item></el-descriptions></el-dialog></div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { salesInvoiceApi,type SalesInvoice } from '@/api/sales/invoice';import { SalesFinanceDocumentStatusEnum } from '@/enums/sales'
const loading=ref(false),rows=ref<SalesInvoice[]>([]),total=ref(0),dateRange=ref<string[]>([]),visible=ref(false),current=ref<SalesInvoice>();const query=reactive({pageNum:1,pageSize:10,invoiceNo:'',customerName:'',status:undefined as number|undefined});const money=(v?:number)=>v==null?'-':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2})
async function load(){loading.value=true;try{const r:any=await salesInvoiceApi.page({...query,startDate:dateRange.value?.[0],endDate:dateRange.value?.[1]});rows.value=r.data?.records||[];total.value=r.data?.total||0}finally{loading.value=false}}function search(){query.pageNum=1;load()}function reset(){query.invoiceNo='';query.customerName='';query.status=undefined;dateRange.value=[];search()}function print(id:number){window.open(`/sales/invoice/print/${id}`,'_blank')}async function detail(id:number){const r:any=await salesInvoiceApi.detail(id);current.value=r.data;visible.value=true}
const details=computed(()=>{const x=current.value;if(!x)return[];return[{label:'发票号',value:x.invoiceNo},{label:'订单ID',value:x.orderId||'-'},{label:'客户',value:x.customerName||'-'},{label:'日期',value:x.invoiceDate||'-'},{label:'税号',value:x.taxpayerId||'-'},{label:'地址/电话',value:`${x.address||'-'} / ${x.phone||'-'}`},{label:'开户行/账号',value:`${x.bankName||'-'} / ${x.bankAccount||'-'}`},{label:'价税合计',value:money(x.totalAmount)},{label:'状态',value:SalesFinanceDocumentStatusEnum.getLabel(x.status)},{label:'备注',value:x.remark||'-'}]});onMounted(load)
</script>
