export { default as SkeletonQuery } from './SkeletonQuery.vue'
export { default as SkeletonStats } from './SkeletonStats.vue'
export { default as SkeletonToolbar } from './SkeletonToolbar.vue'
export { default as SkeletonTable } from './SkeletonTable.vue'
export { default as SkeletonAction } from './SkeletonAction.vue'
