-- 单项 IQC 第三阶段：不合格隔离台账（MySQL 8.x）。
CREATE TABLE inventory_iqc_quarantine (
    quarantine_id BIGINT NOT NULL AUTO_INCREMENT,
    inbound_id BIGINT NOT NULL,
    inbound_item_id BIGINT NOT NULL,
    inspection_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    material_code VARCHAR(100) NULL,
    material_name VARCHAR(255) NULL,
    batch_no VARCHAR(100) NULL,
    quantity DECIMAL(18,4) NOT NULL,
    remaining_quantity DECIMAL(18,4) NOT NULL,
    disposition VARCHAR(32) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    operator_id BIGINT NULL,
    operator_name VARCHAR(100) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (quarantine_id),
    UNIQUE KEY uk_iqc_quarantine_item_inspection (inbound_item_id, inspection_id),
    KEY idx_iqc_quarantine_inbound (inbound_id),
    KEY idx_iqc_quarantine_material_status (material_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IQC不合格品隔离台账';

CREATE TABLE inventory_iqc_disposition_order (
    disposition_id BIGINT NOT NULL AUTO_INCREMENT,
    disposition_no VARCHAR(40) NOT NULL,
    quarantine_id BIGINT NOT NULL,
    inbound_id BIGINT NOT NULL,
    inbound_item_id BIGINT NOT NULL,
    inspection_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL COMMENT 'RELEASE/RETURN/REWORK/SCRAP',
    quantity DECIMAL(18,4) NOT NULL,
    material_code VARCHAR(100) NULL,
    material_name VARCHAR(255) NULL,
    batch_no VARCHAR(100) NULL,
    remark VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    operator_id BIGINT NULL,
    operator_name VARCHAR(100) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (disposition_id),
    UNIQUE KEY uk_iqc_disposition_no (disposition_no),
    KEY idx_iqc_disposition_quarantine (quarantine_id),
    KEY idx_iqc_disposition_inbound (inbound_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IQC隔离处置单';

CREATE TABLE inventory_iqc_return_order (
    return_id BIGINT NOT NULL AUTO_INCREMENT,
    return_no VARCHAR(40) NOT NULL,
    disposition_id BIGINT NOT NULL,
    quarantine_id BIGINT NOT NULL,
    inbound_id BIGINT NOT NULL,
    inbound_item_id BIGINT NOT NULL,
    inspection_id BIGINT NOT NULL,
    supplier_id BIGINT NULL,
    supplier_name VARCHAR(255) NULL,
    material_id BIGINT NOT NULL,
    material_code VARCHAR(100) NULL,
    material_name VARCHAR(255) NULL,
    batch_no VARCHAR(100) NULL,
    quantity DECIMAL(18,4) NOT NULL,
    reason VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    operator_id BIGINT NULL,
    operator_name VARCHAR(100) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (return_id), UNIQUE KEY uk_iqc_return_no (return_no), KEY idx_iqc_return_inbound (inbound_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IQC采购退货单';

CREATE TABLE inventory_iqc_rework_order (
    rework_id BIGINT NOT NULL AUTO_INCREMENT,
    rework_no VARCHAR(40) NOT NULL,
    disposition_id BIGINT NOT NULL,
    quarantine_id BIGINT NOT NULL,
    inbound_id BIGINT NOT NULL,
    inbound_item_id BIGINT NOT NULL,
    inspection_id BIGINT NOT NULL,
    supplier_id BIGINT NULL,
    supplier_name VARCHAR(255) NULL,
    material_id BIGINT NOT NULL,
    material_code VARCHAR(100) NULL,
    material_name VARCHAR(255) NULL,
    batch_no VARCHAR(100) NULL,
    quantity DECIMAL(18,4) NOT NULL,
    reason VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    operator_id BIGINT NULL,
    operator_name VARCHAR(100) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (rework_id), UNIQUE KEY uk_iqc_rework_no (rework_no), KEY idx_iqc_rework_inbound (inbound_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IQC供应商返工单';

CREATE TABLE inventory_iqc_scrap_order (
    scrap_id BIGINT NOT NULL AUTO_INCREMENT,
    scrap_no VARCHAR(40) NOT NULL,
    disposition_id BIGINT NOT NULL,
    quarantine_id BIGINT NOT NULL,
    inbound_id BIGINT NOT NULL,
    inbound_item_id BIGINT NOT NULL,
    inspection_id BIGINT NOT NULL,
    material_id BIGINT NOT NULL,
    material_code VARCHAR(100) NULL,
    material_name VARCHAR(255) NULL,
    batch_no VARCHAR(100) NULL,
    quantity DECIMAL(18,4) NOT NULL,
    reason VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING_APPROVAL',
    applicant_id BIGINT NULL,
    applicant_name VARCHAR(100) NULL,
    approver_id BIGINT NULL,
    approver_name VARCHAR(100) NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (scrap_id), UNIQUE KEY uk_iqc_scrap_no (scrap_no), KEY idx_iqc_scrap_inbound (inbound_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IQC报废审批单';
