-- JJX 内置工序图标字典项
-- 任务：dev-20260912-013
INSERT INTO sys_dict_item
    (dict_code, item_key, item_value, label, remark, sort_order, is_active, tenant_id)
VALUES
('engineering_jjx_icon','上线','上线','上线','{"category":"shangxian","source":"SYSTEM"}',1,1,1),
('engineering_jjx_icon','上线保护膜','上线保护膜','上线保护膜','{"category":"shangxian","source":"SYSTEM"}',2,1,1),
('engineering_jjx_icon','上线冲型','上线冲型','上线冲型','{"category":"shangxian","source":"SYSTEM"}',3,1,1),
('engineering_jjx_icon','上线冲孔','上线冲孔','上线冲孔','{"category":"shangxian","source":"SYSTEM"}',4,1,1),
('engineering_jjx_icon','上线凹凸','上线凹凸','上线凹凸','{"category":"shangxian","source":"SYSTEM"}',5,1,1),
('engineering_jjx_icon','上线加强片','上线加强片','上线加强片','{"category":"shangxian","source":"SYSTEM"}',6,1,1),
('engineering_jjx_icon','上线裁切','上线裁切','上线裁切','{"category":"shangxian","source":"SYSTEM"}',7,1,1),
('engineering_jjx_icon','上线隔片','上线隔片','上线隔片','{"category":"shangxian","source":"SYSTEM"}',8,1,1),
('engineering_jjx_icon','下线','下线','下线','{"category":"xiaxian","source":"SYSTEM"}',9,1,1),
('engineering_jjx_icon','下线保护膜','下线保护膜','下线保护膜','{"category":"xiaxian","source":"SYSTEM"}',10,1,1),
('engineering_jjx_icon','下线冲型','下线冲型','下线冲型','{"category":"xiaxian","source":"SYSTEM"}',11,1,1),
('engineering_jjx_icon','下线冲孔','下线冲孔','下线冲孔','{"category":"xiaxian","source":"SYSTEM"}',12,1,1),
('engineering_jjx_icon','下线加强片','下线加强片','下线加强片','{"category":"xiaxian","source":"SYSTEM"}',13,1,1),
('engineering_jjx_icon','下线背胶','下线背胶','下线背胶','{"category":"xiaxian","source":"SYSTEM"}',14,1,1),
('engineering_jjx_icon','下线裁切','下线裁切','下线裁切','{"category":"xiaxian","source":"SYSTEM"}',15,1,1),
('engineering_jjx_icon','下线连接器','下线连接器','下线连接器','{"category":"xiaxian","source":"SYSTEM"}',16,1,1),
('engineering_jjx_icon','下线隔片','下线隔片','下线隔片','{"category":"xiaxian","source":"SYSTEM"}',17,1,1),
('engineering_jjx_icon','面板','面板','面板','{"category":"mianban","source":"SYSTEM"}',18,1,1),
('engineering_jjx_icon','面板保护膜','面板保护膜','面板保护膜','{"category":"mianban","source":"SYSTEM"}',19,1,1),
('engineering_jjx_icon','面板冲型','面板冲型','面板冲型','{"category":"mianban","source":"SYSTEM"}',20,1,1),
('engineering_jjx_icon','面板冲孔','面板冲孔','面板冲孔','{"category":"mianban","source":"SYSTEM"}',21,1,1),
('engineering_jjx_icon','面板凹凸','面板凹凸','面板凹凸','{"category":"mianban","source":"SYSTEM"}',22,1,1),
('engineering_jjx_icon','面板背胶','面板背胶','面板背胶','{"category":"mianban","source":"SYSTEM"}',23,1,1),
('engineering_jjx_icon','面板裁切','面板裁切','面板裁切','{"category":"mianban","source":"SYSTEM"}',24,1,1),
('engineering_jjx_icon','面板隔片','面板隔片','面板隔片','{"category":"mianban","source":"SYSTEM"}',25,1,1),
('engineering_jjx_icon','弹片','弹片','弹片','{"category":"tanpian","source":"SYSTEM"}',26,1,1),
('engineering_jjx_icon','弹片上贴黑豆','弹片上贴黑豆','弹片上贴黑豆','{"category":"tanpian","source":"SYSTEM"}',27,1,1),
('engineering_jjx_icon','弹片胶带','弹片胶带','弹片胶带','{"category":"tanpian","source":"SYSTEM"}',28,1,1),
('engineering_jjx_icon','包装','包装','包装','{"category":"others","source":"SYSTEM"}',29,1,1),
('engineering_jjx_icon','半成品','半成品','半成品','{"category":"others","source":"SYSTEM"}',30,1,1),
('engineering_jjx_icon','发光二级体','发光二级体','发光二级体','{"category":"others","source":"SYSTEM"}',31,1,1),
('engineering_jjx_icon','品检','品检','品检','{"category":"others","source":"SYSTEM"}',32,1,1),
('engineering_jjx_icon','垫片','垫片','垫片','{"category":"others","source":"SYSTEM"}',33,1,1),
('engineering_jjx_icon','成品','成品','成品','{"category":"others","source":"SYSTEM"}',34,1,1),
('engineering_jjx_icon','打公PIN','打公PIN','打公PIN','{"category":"others","source":"SYSTEM"}',35,1,1),
('engineering_jjx_icon','打母PIN','打母PIN','打母PIN','{"category":"others","source":"SYSTEM"}',36,1,1),
('engineering_jjx_icon','撕水性保护膜','撕水性保护膜','撕水性保护膜','{"category":"others","source":"SYSTEM"}',37,1,1),
('engineering_jjx_icon','测试','测试','测试','{"category":"others","source":"SYSTEM"}',38,1,1),
('engineering_jjx_icon','清洁','清洁','清洁','{"category":"others","source":"SYSTEM"}',39,1,1),
('engineering_jjx_icon','线路加电阻','线路加电阻','线路加电阻','{"category":"others","source":"SYSTEM"}',40,1,1),
('engineering_jjx_icon','线路测阻值','线路测阻值','线路测阻值','{"category":"others","source":"SYSTEM"}',41,1,1),
('engineering_jjx_icon','贴RUBBER胶','贴RUBBER胶','贴RUBBER胶','{"category":"others","source":"SYSTEM"}',42,1,1),
('engineering_jjx_icon','贴周期码','贴周期码','贴周期码','{"category":"others","source":"SYSTEM"}',43,1,1),
('engineering_jjx_icon','贴离型纸','贴离型纸','贴离型纸','{"category":"others","source":"SYSTEM"}',44,1,1)
ON DUPLICATE KEY UPDATE
    item_value = VALUES(item_value), label = VALUES(label), remark = VALUES(remark),
    sort_order = VALUES(sort_order), is_active = VALUES(is_active), deleted = 0;
