-- dev-20260827-026 质量记录模板注册表
CREATE TABLE IF NOT EXISTS quality_template_registry (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  record_no VARCHAR(30) NOT NULL UNIQUE COMMENT '记录编号 JJX-QR-xxx',
  record_name VARCHAR(200) NOT NULL COMMENT '记录名称',
  version VARCHAR(20) DEFAULT 'A' COMMENT '最新版次',
  owner_dept VARCHAR(50) COMMENT '主管部门',
  retention_years INT DEFAULT 2 COMMENT '保存期限(年)',
  category VARCHAR(20) DEFAULT 'blank' COMMENT '类别：blank=空白表 / data=数据联动',
  biz_type VARCHAR(50) NULL COMMENT '数据联动关联业务类型',
  file_id BIGINT NULL COMMENT '模板文件 sys_attachment.id',
  status TINYINT DEFAULT 0 COMMENT '0=草稿 1=生效 2=停用',
  remark VARCHAR(500),
  create_by VARCHAR(64),
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64),
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_status (status),
  KEY idx_dept (owner_dept)
) COMMENT='质量记录模板注册表';

INSERT IGNORE INTO quality_template_registry
  (record_no, record_name, version, owner_dept, retention_years, category, status, remark)
VALUES
('JJX-QR-001', '文件修订申请表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-002', '文件分发确认表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-003', '文件借阅登记表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-004', '受控文件清单', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-005', '制造指令单', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-006', '质量记录一览表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-007', '公司目标策划表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-008', '来料不合格登记表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-009', '岗位能力要求汇总表', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-010', '内部审核计划', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-011', '内部审核日程安排表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-012', '内部审核不符合报告', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-013', '内部审核检查表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-014', '内部审核报告', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-015', '首次会议签到表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-016', '管理评审计划', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-017', '管理评审报告', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-018', '年度培训计划', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-019', '加工贴合治具明细表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-020', '培训签到表', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-021', '员工信息登记表', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-022', '周品质会议', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-023', '供应商评估表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-024', '采购订单', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-025', '合格供应商名单', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-026', '送货单', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-027', '烘烤IR线保养记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-028', '出货交期达成率统计', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-029', '末次会议签到表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-030', '工程变更通知（ECN）', 'A', '工程部', 2, 'blank', 1, NULL),
('JJX-QR-031', '领料单', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-032', '设备设施一览表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-033', '设备维修申请单', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-034', '设备维修记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-035', '生产设备保养记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-036', '设备保养记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-037', '进料检验报告', 'A', '品管部', 2, 'blank', 1, '未来数据联动模板（dev-20260827-028）'),
('JJX-QR-038', '制程检验记录表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-039', '成品检验报告', 'A', '品管部', 2, 'blank', 1, '未来数据联动模板（dev-20260827-028）'),
('JJX-QR-040', '来料异常联络单', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-041', '外校仪器一览表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-042', '温湿度计记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-043', '生产日报表', 'A', '生产部', 2, 'blank', 1, '未来数据联动模板（dev-20260827-028）'),
('JJX-QR-044', '每日生产计划表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-045', '外来文件清单', 'A', '工程部', 2, 'blank', 1, NULL),
('JJX-QR-046', '公司内外环境识别一览表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-047', '合同评审记录表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-048', '合同记录一览表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-049', '客户投诉一览表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-050', '纠正及预防措施表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-051', '顾客满意度调查表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-052', '顾客满意度分析报告', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-053', '合同更改评审单', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-054', '内部异常联络单', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-055', '品质异常改善报告', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-056', '供应商定期评审计划', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-057', '出库/出货表单', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-058', 'QC日报表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-059', '特采联络书', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-060', '办公设备一览表', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-061', '人员增补申请表', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-062', '风险与机遇识别表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-063', '联络单', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-064', '申购单', 'A', '行政部', 2, 'blank', 1, NULL),
('JJX-QR-065', '样品需求单', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-066', '校验通知单', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-067', '校验记录表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-068', '年度校验计划', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-069', '样品客拆记录表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-070', '样品记录表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-071', '变更记录表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-072', '供应商考核统计表', 'A.1', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-073', '返工返修单', 'A', '工程部', 2, 'blank', 1, NULL),
('JJX-QR-074', '供应商评审表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-075', '烘烤记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-076', '员工培训效果评价表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-077', '零件承认书', 'A', '工程部', 2, 'blank', 1, NULL),
('JJX-QR-078', '加班申请单', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-079', '公司相关方要求识别一览表', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-080', '知识管理清单', 'A', '文控中心', 2, 'blank', 1, NULL),
('JJX-QR-081', '品管上岗证', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-082', '印刷首件检查记录表', 'A', '品管部', 2, 'blank', 1, '未来数据联动模板（dev-20260827-028）'),
('JJX-QR-083', '冲型首件检查记录表', 'A', '品管部', 2, 'blank', 1, '未来数据联动模板（dev-20260827-028）'),
('JJX-QR-084', 'IR线烘烤记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-085', '各种油墨使用记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-086', '银浆使用明细表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-087', '模（治）具使用记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-088', '厂商品质履历表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-089', '温湿度计记录表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-090', '出货查检表', 'A', '品管部', 2, 'blank', 1, NULL),
('JJX-QR-091', '客户财产一览表', 'A', '业务部', 2, 'blank', 1, NULL),
('JJX-QR-092', '凹凸参数记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-093', '文件收发记录表', 'A', '工程部', 2, 'blank', 1, NULL),
('JJX-QR-094', '防静电手环测试记录表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-095', '5S现场检查表', 'A', '生产部', 2, 'blank', 1, NULL),
('JJX-QR-096', '半成品入库登记表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-097', '成品入库登记表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-098', '印刷物料签收表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-099', '冲型物料签收表', 'A', '资材部', 2, 'blank', 1, NULL),
('JJX-QR-100', '加工物料签收表', 'A', '资材部', 2, 'blank', 1, NULL);
