-- 208_drop_sales_order_review.sql
-- 任务：dev-20260921-011（OrderReview 死代码/死表清理，看板任务 2029）
-- 背景：OrderReview「平行审核链」已于 dev-20260921-010 删除（11 个写接口全删 + 评审记录改读 system review_flow）。
--       本表 sales_order_review（旧多级审核模型，30+ 列）此后既无写入方也无读取方：
--         · 实体 OrderReviewRecord + OrderReviewRecordMapper（11 条 @Select 全打此表）零引用，已移出仓库
--           （~/jjx-backups/removed-inrepo_20260923/）
--         · 无其它表的外键/列引用；实测 0 行
-- 动作：DROP（幂等）。schema 已存于：表级 guard ~/jjx-backups/sales_order_review_drop_<ts>.sql、
--       jjx-docs/sql/init 子集、历史全库快照 —— 需要时可随时重建。
-- 生效范围：仅删除死表，无数据丢失（0 行）。
DROP TABLE IF EXISTS `sales_order_review`;
