-- risk: high
-- task: dev-20260929-004
-- 删除 IQC 隔离单「状态列」。
-- 背景（history/iqc-disposition-truth-rootfix-dev-20260929-003.md §4.3）：
--   一个状态格子装不下混合处置（实测 IN260929005 隔离单：5 让步 + 2 返工 + 3 退货，
--   状态却被最后写入者盖成 RELEASED），且让步确认入库会无条件覆盖 → 顺序依赖。
-- 口径（用户 2026-09-29 拍板）：唯一状态来源 = 剩余可处置量
--   remaining_quantity > 0 → 待处置；= 0 → 已处置；构成看处置单（让步/退货/返工/报废）。
-- 代码侧已不再读写该列（InventoryIqcQuarantine 实体已移除字段、IqcQuarantineStatusEnum 已删除）；
-- 本迁移只做物理清除。读写顺序无依赖：未执行前多出的列不影响新代码。
ALTER TABLE inventory_iqc_quarantine DROP COLUMN status;
