-- dev-20260929-019; risk: high (event configuration backfill)
-- Source: dev-20260929-018 commit a1e3ed20, jjx-web/src/utils/bizJump.ts.
-- Generated from all 160 sys_event_config rows; 155 enabled. No prefix map is duplicated here.
-- Generator: resolveJump(event_code, '{bizId}') || { path: resolveModulePage(biz_module) }.
-- Query pairs are serialized without escaping the {bizId} template marker.
-- 14 events without a prefix match use the existing module list mapping (listed below).
-- This file is a one-time seed snapshot; new events MUST be configured in the event config page.
-- Preserve non-empty operator configuration on repeat runs; old notifications remain NULL for frontend fallback.
-- Run only through scripts/db-migrate.sh with a verified manual backup.
-- Coverage: SELECT COUNT(*) AS enabled, SUM(NULLIF(TRIM(jump_path),'') IS NOT NULL) AS covered
--           FROM sys_event_config WHERE is_enabled=1;

SET @jump_column_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sys_event_config' AND column_name='jump_path');
SET @jump_ddl = IF(@jump_column_exists=0, 'ALTER TABLE sys_event_config ADD COLUMN jump_path VARCHAR(512) NULL COMMENT ''通知处理路径（配置支持查询参数 {bizId}）''', 'SELECT 1');
PREPARE jump_stmt FROM @jump_ddl;
EXECUTE jump_stmt;
DEALLOCATE PREPARE jump_stmt;

SET @jump_column_exists = (SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sys_notification' AND column_name='jump_path');
SET @jump_ddl = IF(@jump_column_exists=0, 'ALTER TABLE sys_notification ADD COLUMN jump_path VARCHAR(512) NULL COMMENT ''通知处理路径（配置支持查询参数 {bizId}）''', 'SELECT 1');
PREPARE jump_stmt FROM @jump_ddl;
EXECUTE jump_stmt;
DEALLOCATE PREPARE jump_stmt;

START TRANSACTION;
UPDATE sys_event_config SET jump_path = '/biz/requirement' WHERE event_code = 'biz.requirement.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/biz/requirement' WHERE event_code = 'biz.requirement.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/biz/requirement' WHERE event_code = 'biz.requirement.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/bom' WHERE event_code = 'bom.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/bom' WHERE event_code = 'bom.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/inquiry' WHERE event_code = 'inquiry.accepted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/inquiry' WHERE event_code = 'inquiry.converted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/inquiry' WHERE event_code = 'inquiry.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/inquiry' WHERE event_code = 'inquiry.sent' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/alert' WHERE event_code = 'inventory.alert.processed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.cancelled' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.created_from_production' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.created_from_purchase' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/inbound?bizId={bizId}' WHERE event_code = 'inventory.inbound.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stock' WHERE event_code = 'inventory.material_category.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stock' WHERE event_code = 'inventory.material_category.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/material' WHERE event_code = 'inventory.material.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/material' WHERE event_code = 'inventory.material.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/material' WHERE event_code = 'inventory.material.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/material' WHERE event_code = 'inventory.material.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.cancelled' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.created_from_production' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.created_from_sales' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/outbound?bizId={bizId}' WHERE event_code = 'inventory.outbound.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.closed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.data_inputted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.diff_processed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.result_confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.started' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stocktake' WHERE event_code = 'inventory.stocktake.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stock' WHERE event_code = 'inventory.storage_location.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/stock' WHERE event_code = 'inventory.storage_location.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.cancelled' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.confirmed_in' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.confirmed_out' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/transfer' WHERE event_code = 'inventory.transfer.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/warehouse/list' WHERE event_code = 'inventory.warehouse.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/warehouse/list' WHERE event_code = 'inventory.warehouse.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.cancelled' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.completed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.delivering' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.production_started' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.resubmitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.review_started' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.sent_to_customer' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order?bizId={bizId}' WHERE event_code = 'order.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.category.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.category.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.category.deleted_children' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.category.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/resource/film' WHERE event_code = 'product.film.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/resource/film' WHERE event_code = 'product.film.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/resource/film' WHERE event_code = 'product.film.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/resource/film' WHERE event_code = 'product.film.released' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/resource/film' WHERE event_code = 'product.film.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.instance.batch_created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.instance.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.instance.delivered' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.instance.production_completed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.instance.production_started' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.instance.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/route' WHERE event_code = 'product.routing.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/route' WHERE event_code = 'product.routing.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/route' WHERE event_code = 'product.routing.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/engineering/route' WHERE event_code = 'product.routing.version_changed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.standard_process.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.standard_process.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/product/list' WHERE event_code = 'product.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/production/order' WHERE event_code = 'production.completed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/production/order' WHERE event_code = 'production.started' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/production/order' WHERE event_code = 'production.work-report.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/production/order' WHERE event_code = 'production.work-report.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/production/order' WHERE event_code = 'production.work-report.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.arrived' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.document.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.document.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.document.verified' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.item_received' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.material_inquiry.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.material_inquiry.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.material_inquiry.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.material_inquiry.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.payment_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.payment.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.payment.confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.payment.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.payment.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.received' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.supplier.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.supplier.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.supplier.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/purchase/order?bizId={bizId}' WHERE event_code = 'purchase.supplier.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/iqc' WHERE event_code = 'quality.iqc.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/iqc' WHERE event_code = 'quality.iqc.item.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/iqc' WHERE event_code = 'quality.iqc.item.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/iqc' WHERE event_code = 'quality.iqc.quarantine.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/iqc' WHERE event_code = 'quality.iqc.reinspection.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/iqc' WHERE event_code = 'quality.iqc.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.converted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.modified' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.reviewed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.sent' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/quotation?bizId={bizId}' WHERE event_code = 'quotation.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/customer' WHERE event_code = 'sales.customer.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/customer' WHERE event_code = 'sales.customer.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/customer' WHERE event_code = 'sales.customer.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/customer' WHERE event_code = 'sales.customer.status_updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/customer' WHERE event_code = 'sales.customer.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.delivery.received' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.delivery.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.invoice.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.invoice.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.receipt.deleted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.receipt.updated' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.return.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.return.received' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.return.refunded' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/order' WHERE event_code = 'sales.return.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.accepted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.approved' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.cancelled' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.confirmed' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.converted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.created' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.ready' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.rejected' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.rejected_by_customer' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.rejected_by_engineering' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.restarted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.sent' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.started' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.submitted' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.transfer.remind' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/sales/sample-order' WHERE event_code = 'sample.transferred' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/alert' WHERE event_code = 'stock.expiry' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/alert' WHERE event_code = 'stock.low' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/alert' WHERE event_code = 'stock.obsolete' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/alert' WHERE event_code = 'stock.over' AND (jump_path IS NULL OR TRIM(jump_path) = '');
UPDATE sys_event_config SET jump_path = '/inventory/alert' WHERE event_code = 'stock.shortage' AND (jump_path IS NULL OR TRIM(jump_path) = '');
COMMIT;

SELECT COUNT(*) AS enabled_events, SUM(NULLIF(TRIM(jump_path), '') IS NOT NULL) AS covered_events FROM sys_event_config WHERE is_enabled=1;
